const fs = require('fs');
const path = require('path');

const PRICING_DIR = path.join('src', 'services', 'pricing');
if (!fs.existsSync(PRICING_DIR)) fs.mkdirSync(PRICING_DIR, { recursive: true });

fs.writeFileSync(path.join(PRICING_DIR, 'config.pricing.js'), `import { DEFAULT_BASE_WAGE, DEFAULT_MATERIAL_MARKUP, DEFAULT_METAL_COMPLEXITY_MULTIPLIERS, DEFAULT_WHOLESALE_CONFIG, calculateBusinessMultiplier, enforceMinimumBusinessMultiplier } from '@/constants/pricing.constants.mjs';\nexport function getNormalizedSettings(adminSettings = {}) { if (!adminSettings || typeof adminSettings !== 'object') adminSettings = {}; const pricing = adminSettings.pricing || {}; return { baseWage: pricing.wage || DEFAULT_BASE_WAGE, materialMarkup: pricing.materialMarkup || DEFAULT_MATERIAL_MARKUP, administrativeFee: pricing.administrativeFee || 0.10, businessFee: pricing.businessFee || 0.15, consumablesFee: pricing.consumablesFee || 0.05, metalComplexityMultipliers: adminSettings.metalComplexityMultipliers || DEFAULT_METAL_COMPLEXITY_MULTIPLIERS, wholesaleConfig: pricing.wholesaleConfig || DEFAULT_WHOLESALE_CONFIG }; }\nexport function getBusinessMultiplierValue(adminSettings = {}) { const settings = getNormalizedSettings(adminSettings); const multiplier = calculateBusinessMultiplier({ administrativeFee: settings.administrativeFee, businessFee: settings.businessFee, consumablesFee: settings.consumablesFee }); return enforceMinimumBusinessMultiplier(multiplier); }`);

fs.writeFileSync(path.join(PRICING_DIR, 'business.pricing.js'), `import { ERROR_MESSAGES, WHOLESALE_FORMULA_TYPE, DEFAULT_WHOLESALE_CONFIG, enforceMinimumWholesaleMultiplier, calculateBusinessMultiplier } from '@/constants/pricing.constants.mjs';\nimport { getNormalizedSettings, getBusinessMultiplierValue } from './config.pricing.js';\n\nexport function applyBusinessMultiplier(baseCost, adminSettings = {}) { const parsedCost = parseFloat(baseCost); if (isNaN(parsedCost)) throw new TypeError(ERROR_MESSAGES.BASE_COST_MUST_BE_NUMBER); if (parsedCost < 0) throw new RangeError(ERROR_MESSAGES.BASE_COST_CANNOT_BE_NEGATIVE); if (parsedCost === 0) return 0; const enforcedMultiplier = getBusinessMultiplierValue(adminSettings); return Math.round(parsedCost * enforcedMultiplier * 100) / 100; }\n\nexport function calculateWholesalePrice(retailPrice, baseCost, adminSettings = {}) { const parsedRetailPrice = parseFloat(retailPrice); if (isNaN(parsedRetailPrice)) throw new TypeError(ERROR_MESSAGES.RETAIL_PRICE_MUST_BE_NUMBER); if (parsedRetailPrice < 0) throw new RangeError(ERROR_MESSAGES.RETAIL_PRICE_CANNOT_BE_NEGATIVE); const parsedBaseCost = parseFloat(baseCost); if (isNaN(parsedBaseCost)) throw new TypeError(ERROR_MESSAGES.BASE_COST_MUST_BE_NUMBER); if (parsedBaseCost < 0) throw new RangeError(ERROR_MESSAGES.BASE_COST_CANNOT_BE_NEGATIVE); if (parsedRetailPrice < parsedBaseCost) throw new RangeError(ERROR_MESSAGES.RETAIL_PRICE_LESS_THAN_BASE_COST); const settings = getNormalizedSettings(adminSettings); const wholesaleConfig = settings.wholesaleConfig || DEFAULT_WHOLESALE_CONFIG; let wholesalePrice; switch (wholesaleConfig.type) { case WHOLESALE_FORMULA_TYPE.PERCENTAGE_OF_RETAIL: wholesalePrice = parsedRetailPrice * (wholesaleConfig.percentage || 0.5); break; case WHOLESALE_FORMULA_TYPE.BUSINESS_MULTIPLIER_ADJUSTMENT: const businessMultiplier = calculateBusinessMultiplier({ administrativeFee: settings.administrativeFee, businessFee: settings.businessFee, consumablesFee: settings.consumablesFee }); wholesalePrice = parsedBaseCost * (businessMultiplier * (wholesaleConfig.adjustment || 0.75)); break; case WHOLESALE_FORMULA_TYPE.FORMULA_BASED: default: const adminFee = parsedBaseCost * settings.administrativeFee; const businessFee = parsedBaseCost * settings.businessFee; const consumablesFee = parsedBaseCost * settings.consumablesFee; wholesalePrice = ((adminFee + businessFee + consumablesFee) / 2) + parsedBaseCost; break; } const minimumWholesale = parsedBaseCost * enforceMinimumWholesaleMultiplier(1.0); wholesalePrice = Math.max(wholesalePrice, minimumWholesale); return Math.round(wholesalePrice * 100) / 100; }`);

fs.writeFileSync(path.join(PRICING_DIR, 'labor.pricing.js'), `import { DEFAULT_SKILL_LEVEL, VALID_SKILL_LEVELS, ERROR_MESSAGES, isValidSkillLevel, calculateHourlyRateForSkill } from '@/constants/pricing.constants.mjs';\nimport { getNormalizedSettings } from './config.pricing.js';\n\nexport function getHourlyRateForSkill(skillLevel, adminSettings = {}) { if (skillLevel !== undefined && !isValidSkillLevel(skillLevel)) { throw new TypeError(\`\${ERROR_MESSAGES.SKILL_LEVEL_MUST_BE_STRING}. Valid values: \${VALID_SKILL_LEVELS.join(', ')}\`); } const settings = getNormalizedSettings(adminSettings); return calculateHourlyRateForSkill(settings.baseWage, skillLevel); }\n\nexport function calculateLaborCost(laborHours, skillLevel = DEFAULT_SKILL_LEVEL, adminSettings = {}) { const parsedHours = parseFloat(laborHours); if (isNaN(parsedHours)) throw new TypeError(ERROR_MESSAGES.LABOR_HOURS_MUST_BE_NUMBER); if (parsedHours < 0) throw new RangeError(ERROR_MESSAGES.LABOR_HOURS_CANNOT_BE_NEGATIVE); if (skillLevel !== undefined && !isValidSkillLevel(skillLevel)) { throw new TypeError(\`\${ERROR_MESSAGES.SKILL_LEVEL_MUST_BE_STRING}. Valid values: \${VALID_SKILL_LEVELS.join(', ')}\`); } const hourlyRate = getHourlyRateForSkill(skillLevel, adminSettings); return Math.round((parsedHours * hourlyRate) * 100) / 100; }`);

fs.writeFileSync(path.join(PRICING_DIR, 'material.pricing.js'), `import { ERROR_MESSAGES, enforceMinimumMaterialMarkup } from '@/constants/pricing.constants.mjs';\nimport { getNormalizedSettings } from './config.pricing.js';\n\nexport function getMaterialBaseRawCost(material, stullerProduct = null) { if (stullerProduct) { if (stullerProduct.stullerPrice && stullerProduct.stullerPrice > 0) return stullerProduct.stullerPrice; return stullerProduct.unitCost || 0; } if (material.estimatedCost && material.estimatedCost > 0) return material.estimatedCost; return material.unitCost || 0; }\n\nexport function calculateMaterialCost(material, quantity = 1, adminSettings = {}) { if (!material || typeof material !== 'object') throw new TypeError(ERROR_MESSAGES.MATERIAL_MUST_BE_OBJECT); const parsedQuantity = parseFloat(quantity); if (isNaN(parsedQuantity)) throw new TypeError(ERROR_MESSAGES.QUANTITY_MUST_BE_NUMBER); if (parsedQuantity <= 0) throw new RangeError(ERROR_MESSAGES.QUANTITY_MUST_BE_POSITIVE); const settings = getNormalizedSettings(adminSettings); const baseCost = material.estimatedCost || material.costPerPortion || material.unitCost || material.stullerPrice || 0; if (isNaN(baseCost)) throw new TypeError(ERROR_MESSAGES.MATERIAL_COST_MUST_BE_NUMBER); if (baseCost < 0) throw new RangeError(ERROR_MESSAGES.MATERIAL_COST_CANNOT_BE_NEGATIVE); const materialMarkup = enforceMinimumMaterialMarkup(settings.materialMarkup); const markedUpCost = baseCost * materialMarkup; const totalCost = markedUpCost * parsedQuantity; return { baseCost: Math.round(baseCost * 100) / 100, markedUpCost: Math.round(markedUpCost * 100) / 100, materialMarkup: materialMarkup, quantity: parsedQuantity, totalCost: Math.round(totalCost * 100) / 100, calculatedAt: new Date().toISOString() }; }`);

