import { db } from '@/lib/database';
import { randomUUID } from 'crypto';
import Constants from '@/lib/constants';

/**
 * A Casting Batch — one casting order covering a run's pieces (PRODUCTION_RUNS.md §4.1).
 * Ownership-scoped (the owning artisan sees their runs' batches; staff see all). Lifecycle:
 * needs_ordering → ordered (vendor + est) → received (actual cost known → invoice fires, gated
 * from shipping until paid) → delivered → (48h dispute window) → accepted. In-house casting is the
 * same board with `inHouse:true` (no vendor entry — a casting-discipline WO instead).
 */
export const CASTING_STATUS = Object.freeze({
  NEEDS_ORDERING: 'needs_ordering',
  ORDERED: 'ordered',
  RECEIVED: 'received',
  DELIVERED: 'delivered',
  DISPUTED: 'disputed',
  ACCEPTED: 'accepted',
  CANCELLED: 'cancelled',
});

export function validateCastingBatch(data = {}) {
  const errors = [];
  if (!data.ownerId) errors.push('ownerId is required');
  if (!data.designID) errors.push('designID is required');
  if (!Array.isArray(data.pieceIDs) || data.pieceIDs.length === 0) errors.push('pieceIDs[] is required');
  if (data.status && !Object.values(CASTING_STATUS).includes(data.status)) errors.push('invalid casting status');
  return { valid: errors.length === 0, errors };
}

export function buildCastingBatch(data = {}) {
  const now = new Date();
  return {
    batchId: data.batchId || randomUUID(),
    runId: data.runId ?? null,
    ownerId: data.ownerId ?? null,          // owning artisan (run.createdBy / drop owner)
    designID: data.designID ?? null,
    pieceIDs: Array.isArray(data.pieceIDs) ? data.pieceIDs : [],
    status: data.status || CASTING_STATUS.NEEDS_ORDERING,
    inHouse: data.inHouse === true,
    vendor: data.vendor ?? null,
    estCost: data.estCost != null ? Number(data.estCost) : null,
    actualCost: data.actualCost != null ? Number(data.actualCost) : null,
    // Invoice-at-receipt (§4.1). The Stripe invoice itself is generated by the billing rail (S5);
    // this records the amount owed + paid state + the shipping gate.
    charge: data.charge ?? { amount: null, markupRate: null, paid: false, paidAt: null, invoiceID: null },
    shippingGated: data.shippingGated === true,   // true once received+unpaid; nothing ships unpaid
    orderedAt: data.orderedAt ?? null,
    receivedAt: data.receivedAt ?? null,
    deliveredAt: data.deliveredAt ?? null,
    disputeDeadline: data.disputeDeadline ?? null,
    disputedAt: data.disputedAt ?? null,
    disputeReason: data.disputeReason ?? null,
    acceptedAt: data.acceptedAt ?? null,
    createdBy: data.createdBy ?? null,
    createdAt: now,
    updatedAt: now,
  };
}

export default class CastingBatchesModel {
  static COLLECTION = Constants.CASTING_BATCHES_COLLECTION;
  static async collection() { return (await db.connect()).collection(this.COLLECTION); }

  static async ensureIndexes() {
    const col = await this.collection();
    await Promise.all([
      col.createIndex({ batchId: 1 }, { unique: true }),
      col.createIndex({ ownerId: 1, status: 1 }),
      col.createIndex({ runId: 1 }),
      col.createIndex({ status: 1 }),
    ]);
  }

  static async create(data) {
    const batch = buildCastingBatch(data);
    const validation = validateCastingBatch(batch);
    if (!validation.valid) throw new TypeError(validation.errors.join('; '));
    await (await this.collection()).insertOne(batch);
    return batch;
  }

  static async findById(batchId) { return (await this.collection()).findOne({ batchId }, { projection: { _id: 0 } }); }
  static async list(filter = {}) { return (await this.collection()).find(filter, { projection: { _id: 0 } }).sort({ createdAt: -1 }).toArray(); }
  static async findByRun(runId) { return this.list({ runId }); }

  static async updateById(batchId, updateData) {
    await (await this.collection()).updateOne({ batchId }, { $set: { ...updateData, updatedAt: new Date() } });
    return this.findById(batchId);
  }
}
