import { INTERNAL_STATUSES } from './internalStatuses.config';

export const VALID_TRANSITIONS = {
  [INTERNAL_STATUSES.PENDING]: [
    INTERNAL_STATUSES.REVIEWING_REQUEST,
    INTERNAL_STATUSES.IN_CONSULTATION,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.REVIEWING_REQUEST]: [
    INTERNAL_STATUSES.IN_CONSULTATION,
    INTERNAL_STATUSES.AWAITING_CLIENT_INFO,
    INTERNAL_STATUSES.SKETCHING,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.IN_CONSULTATION]: [
    INTERNAL_STATUSES.AWAITING_CLIENT_INFO,
    INTERNAL_STATUSES.SKETCHING,
    INTERNAL_STATUSES.PREPARING_QUOTE,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.AWAITING_CLIENT_INFO]: [
    INTERNAL_STATUSES.IN_CONSULTATION,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.SKETCHING]: [
    INTERNAL_STATUSES.SKETCH_REVIEW,
    INTERNAL_STATUSES.PREPARING_QUOTE,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.SKETCH_REVIEW]: [
    INTERNAL_STATUSES.SKETCH_APPROVED,
    INTERNAL_STATUSES.SKETCHING,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.SKETCH_APPROVED]: [
    INTERNAL_STATUSES.CREATING_CAD,
    INTERNAL_STATUSES.PREPARING_QUOTE,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.CREATING_CAD]: [
    INTERNAL_STATUSES.CAD_REVIEW,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.CAD_REVIEW]: [
    INTERNAL_STATUSES.CAD_APPROVED,
    INTERNAL_STATUSES.CAD_REVISION,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.CAD_REVISION]: [
    INTERNAL_STATUSES.CAD_REVIEW,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.CAD_APPROVED]: [
    INTERNAL_STATUSES.PREPARING_QUOTE,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.PREPARING_QUOTE]: [
    INTERNAL_STATUSES.QUOTE_SENT,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.QUOTE_SENT]: [
    INTERNAL_STATUSES.QUOTE_APPROVED,
    INTERNAL_STATUSES.QUOTE_REVISION,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.QUOTE_REVISION]: [
    INTERNAL_STATUSES.QUOTE_SENT,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.QUOTE_APPROVED]: [
    INTERNAL_STATUSES.DEPOSIT_INVOICE_SENT,
    INTERNAL_STATUSES.ORDERING_MATERIALS,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.DEPOSIT_INVOICE_SENT]: [
    INTERNAL_STATUSES.DEPOSIT_RECEIVED,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.DEPOSIT_RECEIVED]: [
    INTERNAL_STATUSES.ORDERING_MATERIALS,
    INTERNAL_STATUSES.READY_FOR_PRODUCTION,
    INTERNAL_STATUSES.IN_PRODUCTION,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.ORDERING_MATERIALS]: [
    INTERNAL_STATUSES.MATERIALS_RECEIVED,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.MATERIALS_RECEIVED]: [
    INTERNAL_STATUSES.READY_FOR_PRODUCTION,
    INTERNAL_STATUSES.IN_PRODUCTION,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.READY_FOR_PRODUCTION]: [
    INTERNAL_STATUSES.IN_PRODUCTION,
    INTERNAL_STATUSES.CASTING,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.IN_PRODUCTION]: [
    INTERNAL_STATUSES.CASTING,
    INTERNAL_STATUSES.SETTING_STONES,
    INTERNAL_STATUSES.POLISHING,
    INTERNAL_STATUSES.QUALITY_CHECK,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.CASTING]: [
    INTERNAL_STATUSES.SETTING_STONES,
    INTERNAL_STATUSES.POLISHING,
    INTERNAL_STATUSES.QUALITY_CHECK,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.SETTING_STONES]: [
    INTERNAL_STATUSES.POLISHING,
    INTERNAL_STATUSES.QUALITY_CHECK,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.POLISHING]: [
    INTERNAL_STATUSES.QUALITY_CHECK,
    INTERNAL_STATUSES.FINAL_PAYMENT_SENT,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.QUALITY_CHECK]: [
    INTERNAL_STATUSES.FINAL_PAYMENT_SENT,
    INTERNAL_STATUSES.PAID_IN_FULL,
    INTERNAL_STATUSES.READY_FOR_PICKUP,
    INTERNAL_STATUSES.POLISHING, // Back to polishing if issues found
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.FINAL_PAYMENT_SENT]: [
    INTERNAL_STATUSES.PAID_IN_FULL,
    INTERNAL_STATUSES.ON_HOLD,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.PAID_IN_FULL]: [
    INTERNAL_STATUSES.READY_FOR_PICKUP,
    INTERNAL_STATUSES.SHIPPED,
    INTERNAL_STATUSES.DELIVERED,
    INTERNAL_STATUSES.COMPLETED
  ],
  [INTERNAL_STATUSES.READY_FOR_PICKUP]: [
    INTERNAL_STATUSES.DELIVERED,
    INTERNAL_STATUSES.COMPLETED
  ],
  [INTERNAL_STATUSES.SHIPPED]: [
    INTERNAL_STATUSES.DELIVERED,
    INTERNAL_STATUSES.COMPLETED
  ],
  [INTERNAL_STATUSES.DELIVERED]: [
    INTERNAL_STATUSES.COMPLETED
  ],
  [INTERNAL_STATUSES.COMPLETED]: [],
  [INTERNAL_STATUSES.ON_HOLD]: [
    INTERNAL_STATUSES.IN_CONSULTATION,
    INTERNAL_STATUSES.SKETCHING,
    INTERNAL_STATUSES.CREATING_CAD,
    INTERNAL_STATUSES.PREPARING_QUOTE,
    INTERNAL_STATUSES.IN_PRODUCTION,
    INTERNAL_STATUSES.CANCELLED
  ],
  [INTERNAL_STATUSES.CANCELLED]: [
    INTERNAL_STATUSES.REFUNDED
  ],
  [INTERNAL_STATUSES.REFUNDED]: []
};