import { INTERNAL_STATUSES } from './internalStatuses.config';
import { CLIENT_STATUSES } from './clientStatuses.config';

export const INTERNAL_TO_CLIENT_MAPPING = {
  [INTERNAL_STATUSES.PENDING]: CLIENT_STATUSES.PENDING_REVIEW,
  [INTERNAL_STATUSES.REVIEWING_REQUEST]: CLIENT_STATUSES.PENDING_REVIEW,
  [INTERNAL_STATUSES.IN_CONSULTATION]: CLIENT_STATUSES.IN_CONSULTATION,
  [INTERNAL_STATUSES.AWAITING_CLIENT_INFO]: CLIENT_STATUSES.AWAITING_YOUR_RESPONSE,
  
  [INTERNAL_STATUSES.SKETCHING]: CLIENT_STATUSES.IN_DESIGN,
  [INTERNAL_STATUSES.SKETCH_REVIEW]: CLIENT_STATUSES.AWAITING_YOUR_RESPONSE,
  [INTERNAL_STATUSES.SKETCH_APPROVED]: CLIENT_STATUSES.IN_DESIGN,
  [INTERNAL_STATUSES.CREATING_CAD]: CLIENT_STATUSES.IN_DESIGN,
  [INTERNAL_STATUSES.CAD_REVIEW]: CLIENT_STATUSES.AWAITING_YOUR_RESPONSE,
  [INTERNAL_STATUSES.CAD_REVISION]: CLIENT_STATUSES.IN_DESIGN,
  [INTERNAL_STATUSES.CAD_APPROVED]: CLIENT_STATUSES.IN_DESIGN,
  
  [INTERNAL_STATUSES.PREPARING_QUOTE]: CLIENT_STATUSES.QUOTE_PENDING,
  [INTERNAL_STATUSES.QUOTE_SENT]: CLIENT_STATUSES.AWAITING_YOUR_RESPONSE,
  [INTERNAL_STATUSES.QUOTE_REVISION]: CLIENT_STATUSES.QUOTE_PENDING,
  [INTERNAL_STATUSES.QUOTE_APPROVED]: CLIENT_STATUSES.PAYMENT_PENDING,
  
  [INTERNAL_STATUSES.DEPOSIT_INVOICE_SENT]: CLIENT_STATUSES.PAYMENT_PENDING,
  [INTERNAL_STATUSES.DEPOSIT_RECEIVED]: CLIENT_STATUSES.IN_PRODUCTION,
  
  [INTERNAL_STATUSES.ORDERING_MATERIALS]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.MATERIALS_RECEIVED]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.READY_FOR_PRODUCTION]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.IN_PRODUCTION]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.CASTING]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.SETTING_STONES]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.POLISHING]: CLIENT_STATUSES.IN_PRODUCTION,
  [INTERNAL_STATUSES.QUALITY_CHECK]: CLIENT_STATUSES.IN_PRODUCTION,
  
  [INTERNAL_STATUSES.FINAL_PAYMENT_SENT]: CLIENT_STATUSES.PAYMENT_PENDING,
  [INTERNAL_STATUSES.PAID_IN_FULL]: CLIENT_STATUSES.READY_FOR_DELIVERY,
  [INTERNAL_STATUSES.READY_FOR_PICKUP]: CLIENT_STATUSES.READY_FOR_DELIVERY,
  [INTERNAL_STATUSES.SHIPPED]: CLIENT_STATUSES.READY_FOR_DELIVERY,
  [INTERNAL_STATUSES.DELIVERED]: CLIENT_STATUSES.COMPLETED,
  [INTERNAL_STATUSES.COMPLETED]: CLIENT_STATUSES.COMPLETED,
  
  [INTERNAL_STATUSES.ON_HOLD]: CLIENT_STATUSES.ON_HOLD,
  [INTERNAL_STATUSES.CANCELLED]: CLIENT_STATUSES.CANCELLED,
  [INTERNAL_STATUSES.REFUNDED]: CLIENT_STATUSES.CANCELLED
};