import PiecesModel from '@/app/api/pieces/model';
import CastingBatchesModel, { CASTING_STATUS } from '@/app/api/castingBatches/model';

/**
 * Casting board (PRODUCTION_RUNS.md §4.1). Ownership-scoped batch lifecycle with invoice-at-receipt
 * and the nothing-ships-unpaid gate. The Stripe invoice itself is generated by the billing rail
 * (S5) — this service records the amount owed, the paid state, and the shipping gate, and splits
 * the actual casting cost onto the run's piece COGS at receipt.
 */

export class CastingError extends Error {}

/** EFD's markup on fulfilled work (owner: "20% on all COGs"). S5 may source this from settings. */
export const WORK_ORDER_MARKUP_RATE = 0.20;

const round2 = (n) => Math.round((Number(n) || 0) * 100) / 100;

/** The artisan's casting charge = actual vendor cost + EFD markup. PURE. */
export function castingChargeFromCost(actualCost, markupRate = WORK_ORDER_MARKUP_RATE) {
  return round2((Number(actualCost) || 0) * (1 + markupRate));
}

/**
 * Split an actual casting cost across a run's pieces for COGS (equal split; last piece absorbs the
 * rounding remainder so the parts sum exactly to the total). PURE.
 * PROPOSED (overnight, §4g open probe "casting metal → COGS split"): equal per-piece division.
 */
export function splitCastingCost(actualCost, pieceCount) {
  const total = round2(actualCost);
  const n = Math.max(1, Number(pieceCount) || 1);
  const each = round2(total / n);
  const parts = Array.from({ length: n }, () => each);
  parts[n - 1] = round2(total - each * (n - 1));   // remainder on the last piece
  return parts;
}

/** 48h dispute window opens at DELIVERY to the artisan (§4.1). PURE. */
export function disputeDeadlineFrom(deliveredAt, hours = 48) {
  const base = deliveredAt instanceof Date ? deliveredAt : new Date(deliveredAt);
  return new Date(base.getTime() + hours * 3600 * 1000);
}

/** Whether the artisan's dispute window has lapsed (→ auto-accept). PURE. */
export function isPastDisputeWindow(batch, now = new Date()) {
  if (!batch?.disputeDeadline) return false;
  const deadline = batch.disputeDeadline instanceof Date ? batch.disputeDeadline : new Date(batch.disputeDeadline);
  return now.getTime() >= deadline.getTime();
}

const ALLOWED = {
  needs_ordering: ['ordered', 'cancelled'],
  ordered: ['received', 'cancelled'],
  received: ['delivered', 'cancelled'],
  delivered: ['disputed', 'accepted'],
  disputed: ['accepted', 'ordered', 'cancelled'],   // re-order the failed casting or resolve
  accepted: [],
  cancelled: [],
};
/** Validate a lifecycle transition. PURE. */
export function canTransition(from, to) {
  return Boolean(ALLOWED[from]?.includes(to));
}

// ── DB lifecycle ────────────────────────────────────────────────────────────

export async function createCastingBatch({ runId = null, ownerId, designID, pieceIDs, inHouse = false, vendor = null, estCost = null, createdBy = null }) {
  return CastingBatchesModel.create({ runId, ownerId, designID, pieceIDs, inHouse, vendor, estCost, createdBy });
}

async function transition(batchId, to) {
  const batch = await CastingBatchesModel.findById(batchId);
  if (!batch) throw new CastingError('casting batch not found');
  if (!canTransition(batch.status, to)) throw new CastingError(`cannot move casting from ${batch.status} to ${to}`);
  return batch;
}

export async function markCastingOrdered({ batchId, vendor = null, estCost = null }) {
  const batch = await transition(batchId, CASTING_STATUS.ORDERED);
  return CastingBatchesModel.updateById(batchId, {
    status: CASTING_STATUS.ORDERED,
    vendor: vendor ?? batch.vendor,
    estCost: estCost != null ? Number(estCost) : batch.estCost,
    orderedAt: new Date(),
  });
}

/**
 * Receive the casting: the ACTUAL vendor cost is now known. Split it onto the run's piece COGS,
 * fire the artisan charge (actual × 1.20), and gate the batch from shipping until that charge is
 * paid. In-house batches skip the vendor charge/gate (paid via the casting-discipline WO instead).
 */
export async function markCastingReceived({ batchId, actualCost }) {
  const batch = await transition(batchId, CASTING_STATUS.RECEIVED);
  const cost = Number(actualCost);
  if (!(cost >= 0)) throw new CastingError('actualCost must be a non-negative number');

  const parts = splitCastingCost(cost, batch.pieceIDs.length);
  for (let i = 0; i < batch.pieceIDs.length; i += 1) {
    await PiecesModel.upsertMaterialByCategory(batch.pieceIDs[i], 'casting', {
      id: `cast-${batchId}-${i}`,
      name: batch.vendor ? `Casting — ${batch.vendor}` : 'Casting',
      unitCost: parts[i], qty: 1, vendor: batch.vendor ?? '',
    });
  }

  const patch = { status: CASTING_STATUS.RECEIVED, actualCost: round2(cost), receivedAt: new Date() };
  if (batch.inHouse) {
    // In-house self-cast: no vendor invoice, no gate (settled via the casting WO / self-labor).
    patch.charge = { amount: null, markupRate: null, paid: true, paidAt: new Date(), invoiceID: null };
    patch.shippingGated = false;
  } else {
    patch.charge = { amount: castingChargeFromCost(cost), markupRate: WORK_ORDER_MARKUP_RATE, paid: false, paidAt: null, invoiceID: null };
    patch.shippingGated = true;   // nothing ships to the artisan until this is paid
  }
  return CastingBatchesModel.updateById(batchId, patch);
}

/** Record payment of the casting charge (S5/Stripe webhook calls this). Clears the shipping gate. */
export async function markCastingPaid({ batchId, invoiceID = null }) {
  const batch = await CastingBatchesModel.findById(batchId);
  if (!batch) throw new CastingError('casting batch not found');
  return CastingBatchesModel.updateById(batchId, {
    charge: { ...batch.charge, paid: true, paidAt: new Date(), invoiceID: invoiceID ?? batch.charge?.invoiceID ?? null },
    shippingGated: false,
  });
}

/** Ship/hand the casting to the artisan — REFUSED while the charge is unpaid (nothing ships unpaid). */
export async function markCastingDelivered({ batchId }) {
  const batch = await transition(batchId, CASTING_STATUS.DELIVERED);
  if (batch.shippingGated && !batch.charge?.paid) throw new CastingError('casting is gated from shipping until the invoice is paid');
  const deliveredAt = new Date();
  return CastingBatchesModel.updateById(batchId, {
    status: CASTING_STATUS.DELIVERED,
    deliveredAt,
    disputeDeadline: disputeDeadlineFrom(deliveredAt),
  });
}

/** Artisan disputes a delivered casting within the 48h window (§4.1 — casting failure liability). */
export async function disputeCasting({ batchId, reason = null }) {
  const batch = await transition(batchId, CASTING_STATUS.DISPUTED);
  if (isPastDisputeWindow(batch)) throw new CastingError('the 48-hour dispute window has closed');
  return CastingBatchesModel.updateById(batchId, {
    status: CASTING_STATUS.DISPUTED, disputedAt: new Date(), disputeReason: reason,
  });
}

/** Accept a delivered casting (explicit, or auto-accept once the window lapses). */
export async function acceptCasting({ batchId, auto = false }) {
  const batch = await CastingBatchesModel.findById(batchId);
  if (!batch) throw new CastingError('casting batch not found');
  if (batch.status === CASTING_STATUS.ACCEPTED) return batch;
  if (!canTransition(batch.status, CASTING_STATUS.ACCEPTED)) throw new CastingError(`cannot accept casting from ${batch.status}`);
  if (auto && !isPastDisputeWindow(batch)) throw new CastingError('dispute window still open — cannot auto-accept');
  return CastingBatchesModel.updateById(batchId, { status: CASTING_STATUS.ACCEPTED, acceptedAt: new Date() });
}

/** Cancel a casting batch (pre-acceptance). */
export async function cancelCastingBatch({ batchId }) {
  const batch = await transition(batchId, CASTING_STATUS.CANCELLED);
  return CastingBatchesModel.updateById(batchId, { status: CASTING_STATUS.CANCELLED });
}
